- hosts: slaves
  remote_user: root
  vars:
        anaconda_url: https://repo.continuum.io/archive/Anaconda-2.3.0-Linux-x86_64.sh
        tensorflow_url: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
        epel_release_url: https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
        use_local_files: false
  tasks:
      - include: tasks/system-init.yml
      - include: tasks/anaconda.yml
      - include: tasks/anaconda-libs.yml

